services:
  # A Python web service
  - type: web
    name: ams-python-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn render_app:app --bind 0.0.0.0:$PORT --timeout 300
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 10000
    healthCheckPath: / 